services:
  mongo:
    image: mongo:latest
    container_name: phoenix-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: phoenix-backend-api
    ports:
      - "5001:5001"
    environment:
      MONGO_URI: mongodb://mongo:27017/project_phoenix
      NODE_ENV: development
      PORT: 5001
      # Pass secrets from your host machine's .env file
      JWT_SECRET: ${JWT_SECRET}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
    depends_on:
      - mongo
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        # Define the build-time argument for the frontend
        VITE_API_URL: http://localhost:5001/api
    container_name: phoenix-frontend-web
    ports:
      # Map host port 3000 to the container's port 80
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo-data:
